### ISSUE TITLE
Runing with docket got `database` is not open error

### ISSUE THREAD

**Issue by lijiarui** [zixia/wechaty-blinder#4] opened 2017-11-01 21:23 UTC
Trying to use docker version run the repo get the following error.
```
ReadError: Database is not open
    at maybeError (/blinder/node_modules/levelup/lib/levelup.js:288:32)
    at LevelUP.get (/blinder/node_modules/levelup/lib/levelup.js:148:7)
    at FlashStore.<anonymous> (/blinder/node_modules/flash-store/dist/flash-store.js:170:18)
    at step (/blinder/node_modules/flash-store/dist/flash-store.js:4:18)
    at Object.next (/blinder/node_modules/flash-store/bundles/flash-store.umd.js:4:53)
    at /blinder/node_modules/flash-store/dist/flash-store.js:58:46
    at new Promise (<anonymous>)
    at __awaiter (/blinder/node_modules/flash-store/dist/flash-store.js:43:16)
    at FlashStore.get (/blinder/node_modules/flash-store/dist/flash-store.js:160:17)
    at FaceBlinder.<anonymous> (/blinder/node_modules/face-blinder/src/face-blinder.ts:322:47)
    at Generator.next (<anonymous>)
    at /blinder/node_modules/face-blinder/dist/src/face-blinder.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/blinder/node_modules/face-blinder/dist/src/face-blinder.js:3:12)
    at FaceBlinder.remember (/blinder/node_modules/face-blinder/dist/src/face-blinder.js:278:16)
    at FaceBlinder.<anonymous> (/blinder/node_modules/face-blinder/src/face-blinder.ts:261:39)
    at Generator.next (<anonymous>)
    at /blinder/node_modules/face-blinder/dist/src/face-blinder.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/blinder/node_modules/face-blinder/dist/src/face-blinder.js:3:12)
    at FaceBlinder.recognize (/blinder/node_modules/face-blinder/dist/src/face-blinder.js:231:16)
    at /blinder/src/listeners/message.ts:341:40
    at Generator.next (<anonymous>)
    at fulfilled (/blinder/src/listeners/message.ts:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by zixia** [comment] 2017-11-02 04:08
Sorry, I'll close this issue because you did not provide any reproduce steps.

Please feel free to create a new one if you could.

**Closed by zixia** 2017-11-02 04:08 UTC
